### ISSUE TITLE
Petite remarque par rapport au code 

### ISSUE THREAD

**Issue by ksahin** [etalab/ban-geocode#9]
Bonjour, 

N'étant pas expert en Python, ma remarque est à prendre avec des pincettes, mais chez moi j'ai du modifier 2 lignes pour faire fonctionner le projet : 

Dans app.py ligne 30 --> es = elasticsearch.Elasticsearch([{u'host': u'127.0.0.1', u'port': 9200}]) sinon je me prennais une erreur

Ainsi que dans es.py ligne 128 --> reader = csv.DictReader(f, fieldnames=FIELDS, delimiter=',') vu que le csv est délimité par des ',' et non des '|' 

Dernière remarque, dans le readme vous dites que l'import du csv dans elasticsearch devrait prendre 10mn, ça a pris 2h40 chez moi, avec un core 2 duo 2.5 ghz, 8go de ram, et un SSD, je ne sais pas si il y a des paramètres particuliers a elasticsearch qui permettent d'améliorer les perfs ? 

Voilà

**Comment by yohanboniface** [comment]
Pour les remarques sur python, c'est normal, le projet est prévu pour tourner sur python3 ;)

Pour le séparateur, je comprends pas, je l'ai encore téléchargé hier et j'ai bien des pipes. @cquest, une idée?

Pour l'import, humm, aux dernières nouvelles, ça prenait plutôt 45 minutes sur ma machine (SSD? 8Go, Core I7), je crois pas avoir particulièrement tuné ES. Et plus ou moins idem sur le serveur de dev. Peut-être juste une affaire de proc.

**Comment by ksahin** [comment]
J'était bien en Python 3.4.1 pourtant ! Après comme j'y connais pas grand chose en Python, j'ai peut être mal installé quelque chose je ne sais pas. 

Et par rapport au séparateurs, je viens de re-télécharger a l'instant le fichier,  a l'url que vous donnez dans la documentation de l'install (http://bano.openstreetmap.fr/data/full.csv.bz2) et j'ai bien des virgules et pas des pipes. 

Une autre remarques, vous avez oublié de préciser qu'il faut NPM et faire un npm install dans le readme !

Et encore une autre remarque, curl 'http://localhost:5005/api/?q=5 rue Guersant' ça ne marche pas, et ça ne peut pas marcher je pense car la route n'est pas déclaré, c'est /search qu'il faut utiliser n'est-ce pas ?

**Comment by yohanboniface** [comment]
Oui pour `/search/`.

Pour npm, c'est seulement si on veut la page de démo, ce qui n'est pas le but premier de ce repository. Ça peut se préciser comme optionnel. Pull requests acceptées.

Pour le fichier, ce n'est pas le bon. Voici le bon: http://bano.openstreetmap.fr/data/bano-full.csv.gz

@cquest tu pourrais supprimer l'autre? :)

**Comment by cquest** [comment]
full.csv.bz2 est supprimé... pour éviter les confusions. Désolé.

Le 08/01/2015 14:36, Yohan Boniface a écrit :

> Oui pour |/search/|.
> 
> Pour npm, c'est seulement si on veut la page de démo, ce qui n'est pas
> le but premier de ce repository. Ça peut se préciser comme optionnel.
> Pull requests acceptées.
> 
> Pour le fichier, ce n'est pas le bon. Voici le bon:
> http://bano.openstreetmap.fr/data/bano-full.csv.gz
> 
> @cquest https://github.com/cquest tu pourrais supprimer l'autre? :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/etalab/ban-geocode/issues/9#issuecomment-69179344.

## 

Christian Quest - OpenStreetMap France

**Comment by ksahin** [comment]
Par rapport au perfs, 200 ms de temps de réponse moyen sur 10 000 requêtes ça semble normal ? En gros j'ai certaines requêtes très rapide, de l'ordre de 40ms, d'autres qui me prennent 700 ms, n'ayant jamais utilisé elasticsearch je ne sais pas si c'est normal. 

Merci :)

**Comment by yohanboniface** [comment]
C'est plausible, oui. Les requêtes avec beaucoup de termes génériques prennent plus de temps que la moyenne, et y a même quelques cas extrêmes qui peuvent passer la seconde.

Pour info, on est en train de bosser sur un reboot complet, parce qu'on est pas très optimiste sur Elasticsearch: https://github.com/yohanboniface/addok

**Comment by ksahin** [comment]
Le problème que vous avez avec elasticsearch c'est niveau perf ou bien la pertinence des résultats ? 

Et sinon a propos de addok, ça donne quoi niveau perf ? Jvais installer ça pour tester en tout cas, c'est interessant comme projet

Merci beaucoup de me répondre aussi vite :-)

**Comment by yohanboniface** [comment]
> Le problème que vous avez avec elasticsearch c'est niveau perf ou bien la pertinence des résultats? 

Capacité à prendre la main sur les détails de l’algorithmie interne.

> Et sinon a propos de addok, ça donne quoi niveau perf ? Jvais installer ça pour tester en tout cas, c'est interessant comme projet

Les perfs et la pertinence sont meilleures sur addok selon nos tests, mais tant qu'on l'aura pas vu en production, ça reste des estimations.
Pour l'install, je conseille d'attendre un peu, le code change très souvent pour l'instant, y compris sur la modélisation des index.
On vise de le mettre sur adresse.data.gouv.fr très vite néanmoins.

**Comment by cquest** [comment]
Le pb principal d'ElasticSearch c'est son fonctionnement un peu en boite noire.
Il répond bien à 80%, mais pour les 20% restants on est obligé de compliquer énormément en mettant en place des contournements des automatismes d'ES.

C'est classique: un outil générique a du mal à répondre à un problème très spécifique.
ES n'est pas du tout prévu pour traiter des "documents" aussi petits et ressemblants.

Repartir à zéro avec du code qui gère toute la logique de recherche devrait permettre de bien mieux contrôler ce qui se passe. En plus, on constate pour l'instant un gain en performance ;)

**Comment by ksahin** [comment]
En voulant me monter un petit contener docker pour faire tourner l'api, j'ai eu un petit problème dans les logs d'elasticsearch lors de l'insertion des données avec votre nouveau fichier, ce qui est simpa c'est que je n'ai eu aucune erreur de la part du script d'import, il a continuer a tourner jusqu'a 19.xxx millions 

Il n'y aurais pas un petit soucis sur le formatage de la ligne en question ? 

```
2015-01-12 17:27:40,685][DEBUG][action.bulk              ] [Tarantula] [bano-20150112172250][2] failed to execute bulk item (index) index {[bano-20150112172250][place][AUrfL9CbNU0K4aAtwWfP], source[{"context": "03, 46.132411, 3.456961", "street": {"default": "2"}, "housenumber": "24", "type": "Allier", "postcode": "24", "country": "France", "coordinate": {"lat": "Cusset", "lon": "OSM"}, "ordinal": null, "importance": 0.0, "city": {"default": "Rue Saturnin Arloing"}}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
    at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:562)
    at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:490)
    at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:392)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:444)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:150)
    at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:511)
    at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "Cusset"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
    at java.lang.Double.parseDouble(Double.java:540)
    at org.elasticsearch.common.xcontent.support.AbstractXContentParser.doubleValue(AbstractXContentParser.java:182)
    at org.elasticsearch.common.geo.GeoUtils.parseGeoPoint(GeoUtils.java:350)
    at org.elasticsearch.index.mapper.geo.GeoPointFieldMapper.parse(GeoPointFieldMapper.java:529)
    at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:555)
    at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:490)
    at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:541)
    ... 9 more
```

Merci bien

**Comment by yohanboniface** [comment]
Ah, le retour d'"Alexandre |||". @cquest c'est corrigé dans le jeu de données en ligne?
